import Link from "next/link";

export default function SystemPage() {
  return (
    <div className="min-h-screen p-8" style={{ backgroundColor: "rgb(249, 248, 244)" }}>
      <div className="mx-auto w-full max-w-[800px] space-y-8">

        {/* Hero image */}
        <img
          src="/overview/overview-warm.png"
          alt="LOVEABOUT overview"
          className="w-full max-w-[280px] h-auto"
        />

        {/* What I'm Sharing */}
        <div className="space-y-4">
          <h1 className="text-3xl font-semibold text-neutral-900">What I'm Sharing</h1>
          <p className="text-neutral-700 leading-relaxed">
            This isn't a prototype. It's a walkthrough of an idea — what the experience could feel like for the person organizing it and the person receiving it.
          </p>
          <p className="text-neutral-700 leading-relaxed">
            The two journeys below show the emotional arc from both sides. If you want the source material — the messy voice chat, the structured doc, and the tools I used — that's in the <Link href="/process/grok-brainstorm" className="underline hover:text-neutral-900">How I Built This</Link> section.
          </p>
        </div>

        <hr className="border-neutral-200" />

        {/* Design Principles */}
        <div className="space-y-4">
          <h2 className="text-xl font-medium text-neutral-800">Design Principles</h2>
          <p className="text-sm text-neutral-500">The rules I kept coming back to while shaping this.</p>

          <ul className="space-y-3 text-neutral-700">
            <li><strong>Relief, not a task.</strong> If it feels like homework, you've already lost.</li>
            <li><strong>Small ask, big payoff.</strong> Tiny input from the sender, meaningful moment for the receiver.</li>
            <li><strong>No performance, no cringe.</strong> Help people say real things in their own voice — without feeling like a dork.</li>
            <li><strong>AI stays backstage.</strong> It's scaffolding, not the star. Output should read like the sender, not like an app.</li>
            <li><strong>Specificity over sentimentality.</strong> "I love how you ___" beats "I love you so much" every time.</li>
            <li><strong>Fast path to send.</strong> Anything that delays sending is the enemy.</li>
            <li><strong>Low-stakes by design.</strong> Impossible to mess up. The app carries you if you're anxious.</li>
            <li><strong>Respect the receiver's attention.</strong> No feed. No social layer. No "rate your experience." The moment lands, then the app gets out of the way.</li>
            <li><strong>Warm, not cute.</strong> Thoughtful, calm, modern. Not self-care pastel, not startup dashboard, not Hallmark.</li>
            <li><strong>Privacy is a feature.</strong> No public sharing, no contact scraping, no "invite your friends."</li>
            <li><strong>One job, done well.</strong> Make it easier to say something true, quickly, without making it weird.</li>
          </ul>
        </div>

        <hr className="border-neutral-200" />

        {/* Audio section */}
        <div className="space-y-4">
          <h2 className="text-xl font-medium text-neutral-800">Hear the Thinking</h2>
          <p className="text-neutral-600">
            An 11-minute audio walkthrough of the emotional architecture. Generated by NotebookLM from my raw notes.
          </p>
          <audio
            controls
            className="w-full max-w-md"
            src="/process/notebooklm-podcast.mp3"
          >
            Your browser does not support audio.
          </audio>
        </div>

      </div>
    </div>
  );
}
