import Link from "next/link";

export default function SystemPage() {
  return (
    <div className="min-h-screen p-8" style={{ backgroundColor: "rgb(249, 248, 244)" }}>
      <div className="mx-auto w-full max-w-[800px] space-y-8">

        {/* Hero image */}
        <img
          src="/overview/overview-warm.png"
          alt="LOVEABOUT overview"
          className="w-full max-w-[280px] h-auto"
        />

        {/* Title + hook */}
        <div className="space-y-4">
          <h1 className="text-3xl font-semibold text-neutral-900">What is LOVEABOUT?</h1>
          <p className="text-lg text-neutral-700 leading-relaxed">
            A way to give someone the experience of being surrounded by people who love them—without needing everyone in the same room.
          </p>
          <p className="text-neutral-600 leading-relaxed">
            One person organizes, friends contribute short messages, and the recipient gets a private, paced experience they can keep forever.
          </p>
        </div>

        <hr className="border-neutral-200" />

        {/* What you're about to see */}
        <div className="space-y-4">
          <h2 className="text-xl font-medium text-neutral-800">What You're About to See</h2>
          <p className="text-neutral-700 leading-relaxed">
            This isn't a prototype. It's a walkthrough of an idea — what the experience could feel like for the person organizing it and the person receiving it.
          </p>
          <p className="text-neutral-700 leading-relaxed">
            The two journeys below show the emotional arc from both sides. If you want the source material — the messy voice chat, the structured doc, and the tools I used — that's in the <Link href="/process/grok-brainstorm" className="underline hover:text-neutral-900">How I Built This</Link> section.
          </p>
        </div>

        <hr className="border-neutral-200" />

        {/* The core insight */}
        <div className="space-y-4">
          <h2 className="text-xl font-medium text-neutral-800">The Core Insight</h2>
          <p className="text-neutral-700 leading-relaxed">
            This isn't a card. It's not a social post. It's a ceremony — digitized.
          </p>
          <p className="text-neutral-700 leading-relaxed">
            The design prioritizes emotion over features. The technology hides in plain sight.
          </p>
        </div>

        <hr className="border-neutral-200" />

        {/* Why This Works */}
        <div className="space-y-4">
          <h2 className="text-xl font-medium text-neutral-800">Why This Works</h2>
          <ul className="space-y-3 text-neutral-700">
            <li><strong>No app download.</strong> Web-based. The first touchpoint is a text from a friend.</li>
            <li><strong>Not shareable.</strong> Content can't be forwarded or posted. Scarcity is the point.</li>
            <li><strong>No engagement loops.</strong> No likes, no comments. The recipient's only job is to feel it.</li>
            <li><strong>The UI disappears.</strong> Pacing, silence, and restraint do the work.</li>
          </ul>
        </div>

        <hr className="border-neutral-200" />

        {/* Audio section */}
        <div className="space-y-4">
          <h2 className="text-xl font-medium text-neutral-800">Hear the Thinking</h2>
          <p className="text-neutral-600">
            An 11-minute audio walkthrough of the emotional architecture. Generated by NotebookLM from my raw notes.
          </p>
          <audio
            controls
            className="w-full max-w-md"
            src="/process/notebooklm-podcast.mp3"
          >
            Your browser does not support audio.
          </audio>
        </div>

      </div>
    </div>
  );
}
